ExUnit.start()
Faker.start()
Ecto.Adapters.SQL.Sandbox.mode(LiveViewSvelteOfflineDemo.Repo, :manual)
{:ok, _} = Application.ensure_all_started(:wallaby)
Application.put_env(:wallaby, :base_url, LiveViewSvelteOfflineDemoWeb.Endpoint.url())
