---
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: live_view_svelte_offline_demo_dev
      POSTGRES_PASSWORD: postgres
    container_name: live_view_svelte_offline_demo_dev
